### ISSUE TITLE
Connect travis to the repository

### ISSUE THREAD

**Issue by NepheriusIsTaken** [SOEN341-Group1/TemporaryName#23]

**Comment by faisalhabibgit** [comment]
Since we got a duplicate for this on sprint 2. I am wondering how come I don't see this issue on our sprint 2 board we should get rid of either this one or the other one. I just wanted to have one issue for Travis CI

**Comment by NepheriusIsTaken** [comment]
You couldn't see it in the sprint 2 board because I just created the issue without placing it there. It's okay, I've edited the other issue with the correct labels and we'll close this one.
